### ISSUE TITLE
Empty useState by default

### ISSUE THREAD

**Issue by mariaalouisaa** [fac24/paintbox#57]
Maybe not a problem as it seems to be working fine for you, but when I did this in one of the React workshops a mentor mentioned its not good practice to leave the initial state value as nothing.
Maybe you could use null, an empty string, 0 or other falsy value? 

https://github.com/fac24/paintbox/blob/8db93285b8bf77485cc173965cfbac545347a71e/pages/upload.js#L13-L14

**Comment by mubeess** [comment]
Leaving an initial value of useState is a very good practice
