### ISSUE TITLE
🌟 Compliments 🍓

### ISSUE THREAD

**Issue by mariaalouisaa** [fac24/paintbox#58]
- An amazing start on the project - love the flip card affirmation
- Tidy code
- Site is easy to navigate, obvious what to do from a users perspective

**Comment by sonianb** [comment]
Also, very interesting to see some styled components and supabase code,  which I hadn't seen before.

**Comment by lascellesabercrombie** [comment]
- attentive to modularisation
- thoughtful consideration of users (e.g. choice to set public vs private on upload)
- in general, seems like a really rich, carefully-considered app that's well on the way to being fully functional!
